### ISSUE TITLE
Separate projection from query execution

### ISSUE THREAD

**Issue by timowest** [querydsl/querydsl#1120]
e.g.

```java
query.from(customer).where(customer.firstName.eq("Tom")).list(customer)
```

into

```java
query.select(customer).from(customer).where(customer.firstName.eq("Tom")).list()
```

This has the following benefits

* queries can be written both with select definition in the beginning as well as the end
* subqueries can be defined via normal Query instances
* Projectable and SimpleProjectable can be merged into the same class

Disadvantages
* more verbose syntax in some cases
* generic parameter in Query interface/class

**Comment by BuBuaBu** [comment]
I like this new syntax, this is more "fluent"

Did you also plan to add a method like com.querydsl.sql.ProjectableSQLQuery.getSQL() ?
Otherwise, we will not be able to call either list() or getSQL() for the same query.

**Comment by timowest** [comment]
getSQL() will be available also in the new version.

**Comment by cowwoc** [comment]
I currently waste a lot of time trying to figure out how to convert arbitrary SQL statements into QueryDSL syntax (and I've been using QueryDSL for a while). I like this change because it eases this pain.

I hope you continue moving in this direction. Non-standard expressions are also a pain point (e.g. "SELECT <constant>" or "SELECT function(x)" etc... The fact that we have to reach over to classes like `com.mysema.query.support.Expressions` makes the API harder to learn because it's not clear what are options are at any given point when building the query. Ideally I should be able to figure out what my options are without navigating away from the IDE's code-complete :)

**Comment by timowest** [comment]
I suggest that rename a few methods from Projectable to have a clear separation between query construction and fetching

* list -> fetch
* iterate -> fetchIterate ?!?
* firstResult -> fetchFirst / fetchOne / fetchAny
* uniqueResult -> fetchUnique / fetchOne
* listResults -> fetchResults
* count -> fetchCount

Otherwise there will be clashes for exists, notExists, count which are useful both in expression form and as fetch results. What do you think?

**Comment by timowest** [comment]
@cowwoc `Expressions` contains mostly factory methods for custom expression creation. In normal situations you won't be using this class much.

**Comment by cowwoc** [comment]
@timowest I favor introducing an intermediate `execute()` call and leaving the method names unchanged.

Example: `query.select(customer).from(customer).where(customer.firstName.eq("Tom")).execute().list()`

where `execute()` would return some sort of result type, and `list()` would convert the result into a list.

**Comment by cowwoc** [comment]
Regarding `Expressions` I find myself using it 10-25% of the time. As such, I think it is should be easier to discover/use.

**Comment by Shredder121** [comment]
> @timowest I favor introducing an intermediate execute() call and leaving the method names unchanged.

Could you elaborate on why you favor this?


> where execute() would return some sort of result type, and list() would convert the result into a list.

This has some implications on complexity, since the intermediate 'result' should have to know what state it is in and what results *can* be expected, (e.g. iteration is something special entirely).

Also, we already have the projection type in the Query, so I think it is best to keep the result processing local to the Query class of the module.

**Comment by timowest** [comment]
@cowwoc `execute()` as you describe it is not feasible, since the different projection methods have also different result fetching behaviour
* list = eager loading of all results
* iterate = lazy iteration
* firstResult = only first loaded
* uniqueResult = first two loaded
* listResults = eager results and total count for paging
* count = only count

`execute()` implies that the query is executed, when the method is called.

**Comment by timowest** [comment]
@cowwoc Concerning `Expressions` usage feel free to sketch a more fluent usage pattern for the functionality it provides.

**Comment by cowwoc** [comment]
> Could you elaborate on why you favor this?

My intent was to:

* Visually separate query construction from query execution (fetching the results).
* In the existing API (even the one you are proposing) it isn't obvious at which point the query is actually getting fired. With the API I was thinking users could potentially construct a query once and reuse it multiple times, potentially reading the results differently each time (once as a list, once as an iterator, etc).

These points come about from my impression that there is a performance gain to be had if we can reuse PreparedStatements (something that QueryDSL does not currently allow). However, if there is no benefit to this (because, say, connection pools already do this) then I withdraw my suggestion.

@timowest The methods you listed seem to violate the "query construction" vs "query execution" separation of concerns. For example, it sounds as if `count()` alters the query but the entire point of this issue is to move the query construction components to the beginning of the line.

The methods you listed seem to blur the line a bit between query construction vs execution vs enforcing assertions on the response. I would expect users to `select(Expressions.count(customer)).from(customer).where(...).fetchFirst(Integer.class)`.

How about this syntax (v2)?

`select(...columns...).from(...tables...).where(...conditions...).X()` where `X()` is one of:

* `fetchFirst().as(C)` fetches up to one row and casts it to an instance of type `C`
* `hasMaxRows(1).fetchFirst().as(C)` fetches up to two rows, ensures that there is only one, and casts the result to an instance of type `C`
* `fetchList().of(C)` fetches all rows and cast them to a `List<C>`
* `iterate().as(C)` lazy iteration over the rows as a `Iterator<C>`

Notice that I moved the assertions in front of the fetching operation, because `hasMaxRows(1).fetchList().of(C)` is legal too (I'd expect this to return a list of zero or one elements).

and this opens up the door to future assertions.

For `count()` we'd do something along the lines of:

`select(Expressions.count(customer)).from(customer).where(...).fetchFirst().as(Integer.class)` ... I like how this reads a lot closer to raw SQL/JDBC code (lower learning curve).

As for making `Expressions` more discoverable, I guess we could start off by using them more frequently in the documentation (show at least 2-3 different examples showcasing things like invoking `count()`, user functions, advanced expressions, etc)

**Comment by timowest** [comment]
You are right that the count options are redundant for the querydsl modules
that allow to define a projection.

The queries will be typed, so the as invocations are not necessary. The
type parameter of the query is the element type of the result.

**Comment by timowest** [comment]
here are the Projectable/Fetchable method names for review, the first option is the current choice and the second an alternative
* list -> fetch or fetchAll
* iterate -> fetchIterate or iterate
* firstResult -> fetchFirst or fetch
* uniqueResult -> fetchOne
* listResults -> fetchResults
* count -> fetchCount

at least fetchIterate feels weird, so maybe iterate is better? what about the others?

**Comment by cowwoc** [comment]
I like the second option for all methods.

**Comment by cowwoc** [comment]
Correction. I like fetchAll, iterate (second option) but then fetchFirst (first option).

**Comment by cowwoc** [comment]
For fetchOne, consider fetchOnlyOne instead. The latter implies there must be only one, whereas the former sounds like "give me any one".

**Comment by timowest** [comment]
I'd still like to keep the `fetch` variant as the default, since returning all matching results feels like a reasonable default behaviour, so
* list -> fetch
* iterate (no change)
* firstResult -> fetchFirst
* uniqueResult -> fetchOne
* listResults -> fetchResults
* count -> fetchCount

**Comment by fanste** [comment]
Sorry for this late comment on that issue, but got the map()-method removed?

**Comment by Shredder121** [comment]
We did move the projection logic to `Projections`.
So getting a Map result could be done like this:
```java
query()
.select(Projections.map(employee.firstname, employee.lastname))
.from(employee)
.fetch()
```

**Comment by RishuK** [comment]
What about the alternative for a list method that take a parameter?
