### ISSUE TITLE
Is there any way to do a TRUNCATE TABLE with QueryDSL?

### ISSUE THREAD

**Issue by renanleandrof** [querydsl/querydsl#1146]
I want to do something like the 
new JPADeleteClause(this.entityManager, QTable);

but instead a DELETE ALL a TRUNCATE would be nice.

**Comment by timowest** [comment]
Hi.

Truncate table is afaik not supported via jpql, also Querydsl SQL doesn't
support it.

Timo

**Comment by Shredder121** [comment]
Indeed.
JPA only allows access to the database via its EntityManager.
Although you can execute arbitrary SQL using native queries, I don't think it's intended, useful, common or safe to execute commands like that.

Since truncate is a DDL statement, it would bypass logs and (specific) referential integrity checks.

We support DQL and DML statements, which are always supported, recommended, good practice in the field and so on.

I hope these comments answered your questions.
