### ISSUE TITLE
RFE: Ability to configure export update policy

### ISSUE THREAD

**Issue by cowwoc** [querydsl/querydsl#1309]
I am attempting to use the Maven querydsl export plugin to generating the QTables.

One of my clients has many database tables, and the database connection is very slow. As a result, the export process takes multiple minutes and re-runs every single time I recompile my code.

My goal is to speed up this process, ideally by avoiding trying to export tables which have not changed but I don't think you can detect whether a table has actually changed without first looking it up.

Instead, I'd like to propose we adopt a mechanism similar to Maven's `updatePolicy`:

```
updatePolicy (String): The frequency for downloading updates - can be "always", "daily" (default), "interval:XXX" (in minutes) or "never" (only if it doesn't exist locally).
```

see http://maven.apache.org/ref/3.3.1/maven-settings/settings.html

**Comment by Shredder121** [comment]
The policy we use(at work), and which is very scalable, is that we make an `ExporterUtil` unit test.
Then periodically (when we actually change something) we run that test to update the sources.

But we could see if we can emulate behavior like this, since it sounds like a good addition.
@timowest @johnktims what do you think?

**Comment by timowest** [comment]
Sounds like a good addition to the plugin.
