### ISSUE TITLE
Enable auto-discovery for APT

### ISSUE THREAD

**Issue by bsideup** [querydsl/querydsl#1335]
Hey guys!

For tools like Gradle it would be really cool to add `META-INF/services/javax.annotation.processing.Processor` file according to: http://docs.oracle.com/javase/6/docs/technotes/guides/apt/GettingStarted.html

It will allow javac to auto-discover QueryDSL APT processor, so there will be no need to configure javac during Gradle build. 

This is the same what Lombok did: 
https://github.com/rzwitserloot/lombok/blob/e45b492bb007af43301799f2e338a509a6389888/build.xml#L229

**Comment by bsideup** [comment]
Sorry. Didn't know about APT-JPA.

**Comment by punkstarman** [comment]
Why was this issue closed? I think the point is valid.

If not, it would be nice to have a comment on why, for posterity's sake.

**Comment by Shredder121** [comment]
For the `querydsl-apt` artifacts we set up classifiers, for `jpa` and the like.
Those have the services set up accordingly.

**Comment by xak2000** [comment]
@Shredder121 I didn't know about classifiers (and what it is), so after some digging I understand your answer. I think this feature is not very often used because I never heared about it.

So, for posterity's sake:

There is an example in the official docs for **maven**, but for **gradle**, the one should add classifier at the end of dependency string:

```
annotationProcessor "com.querydsl:querydsl-apt:${property('querydsl.version')}:jpa"
```

(note: `jpa` at the end of dependency version - it is `classifier`)

Or full version:

```
annotationProcessor group: 'com.querydsl', name: 'querydsl-apt', version: property('querydsl.version'), classifier: 'jpa'
```

With this configuration `com.querydsl.apt.jpa.JPAAnnotationProcessor` is automatically detected by `javac` (and gradle).
