### ISSUE TITLE
BeanPath.casts should be made safe for concurrent usage

### ISSUE THREAD

**Issue by timowest** [querydsl/querydsl#1403]
BeanPath.casts should be made safe for concurrent usage

**Comment by bataras** [comment]
This and other instance fields in the hierarchy appear to make this usage pattern non-threadsafe...

JPAQuery query = getQuery();
QPartner partner = QPartner.partner; // not threadsafe due to static implementation
Partner p = query.from(partner)....

Ie, implementing a repository pattern may not be reliable.

**Comment by timowest** [comment]
Why do you think is the usage of the static default variable non threadsafe?
