### ISSUE TITLE
Spring-Data/MongoDB/QueryDSL Searching nested _id of ObjectId type

### ISSUE THREAD

**Issue by bc15** [querydsl/querydsl#1525]
When an document from a collection is nested inside a document of another collection, it's pretty standard to make a copy of the nested document verbatim instead of creating another type of document just for the sake of nesting. Ex:

    category {"_id": ObjectId("c1"), "name": "Category 1"}
    question {"_id": ObjectId("q1"), category: {"_id": ObjectId("c1"), "name": "Category 1"}}

When using queryDSL as follows:

    question.category.id = "c1"

queryDSL generates a query like this:

    "question.category._id":"c1"

where I expect:

    "question.category._id":ObjectId("c1")

This works for top level documents, not for nested. I think this is a valid case and Spring should do the same translations it does for top level search. Is there a workaround for that?

see http://stackoverflow.com/questions/31249917/spring-data-mongodb-querydsl-searching-nested-id-of-objectid-type

**Comment by vespermetsu** [comment]
I'm still having the same issue as described above. Here's what I was doing:

@Entity

public abstract class BaseEntity implements Serializable {

    @Id

    private String id;

..



@Document

@Entity

public class Company extends BaseEntity {

..



public class ActivitySchedule extends BaseEntity {

    @NotNull

    private Company company;

..

My predicate is as follow... 

builder = new BooleanBuilder();

activitySchedule = QActivitySchedule.activitySchedule;

builder.and(activitySchedule.company.id.eq(companyId));

This works for top level document perfectly but when i try to search nested document by id, it just can't be found. Other string field is fine though, except id.

I suspect that the problem is due to the following:

MongodbSerializer.java

+    protected boolean isId(Path<?> arg) {
+        // TODO override in subclass
+        return false;
+    }

Shouldn't it be something like Morphia version? (MorphiaSerializer.java)
     @Override
+    protected boolean isId(Path<?> arg) {
+        return arg.getAnnotatedElement().isAnnotationPresent(Id.class);
+    }

Thanks!

**Comment by timowest** [comment]
MongodbSerializer is an abstract superclass, the template methods should be overriden by subclasses. They have dummy implementations because of backwards compatibility.

**Comment by vespermetsu** [comment]
Currently my project doesn't use Morphia. Does this mean that I need to use Morphia to get this working? From http://www.querydsl.com/static/querydsl/4.0.7/apidocs/com/querydsl/mongodb/MongodbSerializer.html the only subclass I see is MorphiaSerializer..  Sorry I don't know how querydsl work internally but If I don't use MorphiaSerializer, which code is then responsible for the serialization?

Thanks!

**Comment by timowest** [comment]
The problem is on the Spring Data side. You should report the problem there.
