### ISSUE TITLE
In querydsl-jpa on Oracle, StringExpression.matches should call REGEXP_LIKE

### ISSUE THREAD

**Issue by robertandrewbain** [querydsl/querydsl#1713]
Based on http://stackoverflow.com/questions/33915650/regular-expression-matching-in-querydsl.

Using querydsl-jpa 3.6.9 on Oracle 11G, calling `public BooleanExpression matches(Expression<String> regex)` on a `StringExpression`  should result in a call to `REGEXP_LIKE` but instead is converted to a normal `LIKE`.

**Comment by robertandrewbain** [comment]
I will investigate this.

**Comment by schlebe** [comment]
I have the same problem and I'm using QueryDsl 3.6.0.

Is there a version where this issue is corrected ?

I work currently with Oracle 10g and JAVA 6.

**Comment by schlebe** [comment]
I have migrated my application to Glassfish 4.1 and I have also migrated QueryDsl from 3.6.0 to 3.7.2.
... but I have always the same mistake.

**Comment by schlebe** [comment]
I have found a workaround to this problem when, suddently I'm thinking how I can call through QueryDSL a custom function defined on Oracle because a REGEXP_LIKE is similar to a function !

My problem is that I have a column's table that contains a list of sale's codes separated by comma like A45,Z67,T12

The user will search if the list-field contains a specific sale's code with or without pattern * like searching Z67 or T1* or *4*.

Since "matches" functions replace Regex pattern by Like pattern, my code previous will be

`
String sValue = criteria.getSalesCode();
        
if (sValue.startsWith("*") && sValue.endsWith("*"))
    {
    jpaQuery = jpaQuery.where(q.salesCodeList.like(sValue.replace('*','%')));
    }
else
if (sValue.startsWith("*"))
    {
    jpaQuery = jpaQuery.where(q.salesCodeList.like(sValue.replace('*','%')).or(q.salesCodeList.like(sValue.replace('*','%') + ",%")));
    }
else
if (sValue.endsWith("*"))
    {
    jpaQuery = jpaQuery.where(q.salesCodeList.like(sValue.replace('*','%')).or(q.salesCodeList.like("%," + sValue.replace('*','%'))));
    }
else
    {
    jpaQuery 
        = jpaQuery
            .where(q.salesCodeList.eq(sValue)
                .or(q.salesCodeList.like(sValue + ",%"))
                .or(q.salesCodeList.like("%," + sValue))
                .or(q.salesCodeList.like("%," + sValue + ",%"))
            );
    }
`

Now, the solution (found on Internet) is simpler !

`
String sValue = criteria.getSalesCode();
String sRegex = "(^|,)" + sValue.replace("%","[^,]*") + "(,|$)"; 
jpaQuery = jpaQuery.where(Expressions.booleanTemplate("function('REGEXP_LIKE', {0}, {1})", q.salesCodeList, sRegex));
`

Thanks to [http://stackoverflow.com/questions/22984343/how-to-call-mysql-function-using-querydsl](http://stackoverflow.com/questions/22984343/how-to-call-mysql-function-using-querydsl)

CAUTION: this is a workaround !
