### ISSUE TITLE
JPAQuery being improperly generated

### ISSUE THREAD

**Issue by ErikVanNorstrand** [querydsl/querydsl#1799]
This bug is quite weird, as I feel like it shouldn't be happening at all, I am hoping that I have somehow done something incredibly stupid, and after the solution is found it will be user error.

To make things a bit easier, I have created a tiny project that causes the exact error to happen when unit tests are run.

https://github.com/ErikVanNorstrand/SpringBootQueryDSLJPAExample

If you check out the project, and run the unit tests, you should get the following results:

ContextLoads: Pass
CreateDataEntity: Pass
GetDataEntity: Pass
GetDataEntityTwo: Fail

The ONLY difference between the two getDataEntity modules, is the first one gets an entity using the JPARepository, while the second one uses JPAQuery.

The error that is generated when the JPAQuery function is called is below:
Caused by: java.lang.IllegalArgumentException: org.hibernate.hql.internal.ast.QuerySyntaxException: unexpected token: from near line 2, column 1 [select from test.DataEntity dataEntity where dataEntity.test1 = ?1]

What seems to be happening, is the JPAQuery is generating a bad query, that when run against the internal H2 database, fails. I assume if the query was [select from dataEntity where dataEntity.test1 = ?1] things would work just fine.

Any assistance would be greatly appreciated!

**Comment by Shredder121** [comment]
Well, it seems the issue is fairly trivial.
The problem isn't that the query is `select from [test.]DataEntity`, because that is the package name, so it would be fine HQL/JPQL.
The problem starts with `select [] from ...`, nothing is in the select list.
[This is because there should still be a projection](https://github.com/ErikVanNorstrand/SpringBootQueryDSLJPAExample/compare/master...Shredder121:bean-fix).
[Alternatively, you can also select the QDataEntity directly](https://github.com/ErikVanNorstrand/SpringBootQueryDSLJPAExample/compare/master...Shredder121:select-fix).

**Comment by ErikVanNorstrand** [comment]
Man I feel stupid now...

Thank you for the quick response!
