### ISSUE TITLE
Consider repackaging guava to prevent dependency conflict

### ISSUE THREAD

**Issue by akiraly** [querydsl/querydsl#2038]
As guava upgrade comes up from time to time (#835 , #931) and querydsl is currently on v18 while the latest stable is v19 (and soon google will release v20) did you consider to just repackage the guava version that querydsl is using?
For example by using the [maven shade plugin](http://maven.apache.org/plugins/maven-shade-plugin/examples/class-relocation.html).

This way querydsl would allow its consumers to use any guava version they want (which would be great considering guava is not a backward compatible library).

**Comment by Shredder121** [comment]
We already have artifacts named `*-one-jar`.
Could you verify that that is what you need?
If you really mean the relocation of classes to another package, I'm not sure about that.

If guava were a purely internal library, then I think shading is a good idea.

The issue is that we also accept guava Functions for functionality, which would mean that the current Functions are not of the same type, and converting from/to those Functions is then a burden on the consumer.

**Comment by akiraly** [comment]
I was thinking about the relocation to a different package.

For people using java8 the api change would probably not be too problematic as the lambda expressions could be recompiled against the "new" packages as well.

But I understand that this would be a bigger change for java6/7 users.

**Comment by amanteaux** [comment]
Is there currently a problem with a newer version of Guava ?
In about 10 projects we are using Guava 19 with Querydsl and we haven't noticed any incompatibility bug between these 2 libraries.

If there isn't any serious incompatibility issue, I am not sure repackaging Guava is such a good idea. Here is 2 drawbacks that will occur if Guava is repackaged:

- when one will try to use a Guava API, he will have to check he didn't import the repackaged version class (it is already a pain with Jersey and its Guava repackaged version :/)
- Guava is a 1.3Mo library, repackaging it will mean projects using Querydsl will be 1.3Mo heavier.

If conflicts do occur with Guava, maybe just copy/pasting the Guava classes that are used into Querydsl may be better. This approach would enable:
- to restrict Guava classes visibility,
- to reduce the size of the "repackaged" Guava.

This approach has successfully been implemented in jOOQ: <https://blog.jooq.org/2016/08/11/all-libraries-should-follow-a-zero-dependency-policy/>

**Comment by aquincum** [comment]
FYI:

We have encountered a dependency conflict issue with Guava: the Azure keyvault SDK relies on Guava 20 and we tracked down the conflict to the querydsl library. We placed a dependency in our main pom on Guava 20, and now everybody seems to be playing nicely with each other.

**Comment by ratcashdev** [comment]
The best would be not to rely on guava at all. I wonder that with regards to JDK8 or even JDK9 if there's still something essential in guava?

**Comment by Shredder121** [comment]
- Immutable collections(which we could replace with unmodifiable collections)
- functions (which are in jdk8, I know)
- caches (which we could replace with another library like caffeine, but 1) does a cache library pull enough merit? would we then not just move the 'keep synchronized with upstream' to another dependency?).

Just to jot down a few things, let me know your thoughts.

**Comment by ratcashdev** [comment]
The less the dependencies, the better (faster builds, less exposure to third parties and their bugs/responsiveness). But replacing one dependency with a different one at the cost of couple (tens?) of MDs just to save a couple of bytes, is probably not a good idea.
But if you could just carve out a couple of classes providing the cache (i.e. the banana, without requiring the gorilla holding the banana and the whole jungle around him) and make that an integral part of querydsl I think that would deserve some consideration with regards to the (above mentioned) benefits.

**Comment by ben-manes** [comment]
It looks like there is [one usage](https://github.com/querydsl/querydsl/blob/8f96f416270d0353f90a6551547906f3c217833a/querydsl-core/src/main/java/com/querydsl/core/alias/AliasFactory.java) of `CacheBuilder`, which is unbounded and used for self populating. That could be replaced with `ConcurrentHashMap#computeIfAbsent`, though do not it locks [pessimistically](https://github.com/ben-manes/caffeine/wiki/Benchmarks#compute) in JDK8. In JDK9 it now has partial prescreening, but I haven't benchmarked that version. Is there another usage that I am missing? 

It does look fairly easy to remove Guava from being a runtime dependency (probably no issue for the codegen and tests). But do note that Guava changed its compatibility guarantee to be much more forgiving by not removing deprecated methods, rather than the 2 year cycle.

**Comment by natros** [comment]
New Guava compatibility policy
https://groups.google.com/forum/?fromgroups#!topic/guava-discuss/rX-QXo-67ZU

**Comment by jwgmeligmeyling** [comment]
The dependency on Guava was removed with #2676
