### ISSUE TITLE
SQLExpressions.unionAll returns "No connection provided"

### ISSUE THREAD

**Issue by pvanhon1** [querydsl/querydsl#2068]
using querydsl version 4.1.4

The connection info is not filled in when using SQLExpressions.unionAll. 
```
JPAQueryFactory queryFactory = new JPAQueryFactory(entityManager);
JPAQuery jpaQuery1 = queryFactory.select(Expressions.constant("abc"), QAlertOverview.alertOverview.alertId.count()).from(QAlertOverview.alertOverview);
JPAQuery jpaQuery2 =  queryFactory.select(Expressions.constant("def"), QAlert.alert.id.count()).from(QAlert.alert);
List list1 = jpaQuery1. fetch();
List list2 = jpaQuery2. fetch();
List list1and2 = SQLExpressions.unionAll(jpaQuery1, jpaQuery2).fetch();
```

The fetch of list1 and list2 work correctly while fetch of list1and2 throw "java.lang.IllegalStateException: No connection provided", which is logical since SQLExpressions.unionAll does not copy connection info;

What's the correct way of executing the unionized query? 
Thanks!

**Comment by Shredder121** [comment]
*huh*. Interesting that we never found this.
This indeed shouldn't work.

The process should be [like this](https://github.com/querydsl/querydsl/blob/b40b4928f0ffa640770ad9405082a93865c73255/querydsl-sql/src/test/java/com/querydsl/sql/UnionBase.java#L62-L69).
So you would need *a* query with connection information, and call `union` or `unionAll` and work from there.

@querydsl/developers I think it's best if we remove these methods, don't you think?
Would it be reasonable to just remove them (since they don't work) or remove them with Querydsl 5 or so?
