### ISSUE TITLE
MongodbSerializer need update for IN/NOT_IN operation for  @DBRef 

### ISSUE THREAD

**Issue by btpka3** [querydsl/querydsl#2133]
I am using spring boot 1.5.2.RELEASE and querydsl-mongodb 4.1.4. Found this:

```java
@Document
public class User {
    @DBRef
    private Addr addr;
}
```
and query like this:

```java
List<Addr> addrList = ...;
return userRepo.findAll(Expressions.allOf(
        QUser.user.addr.notIn(addrList)  // ONLY worked when addrList.size() == 1
))
```

this may refered to [MongodbSerializer#visit(Operation<?> expr, Void context)](https://github.com/querydsl/querydsl/blob/master/querydsl-mongodb/src/main/java/com/querydsl/mongodb/MongodbSerializer.java#L213) which not  invoke `convert` properbly?

So, could this be fixed ? or give some other alternative way?

PS: current I using this :

```groovy
// groovy code
    List<BooleanExpression> neAddrs = addrList.findResults { QUser.user.addr.ne(it) }.toList()
    return userRepo.findAll(allOf(
            allOf((BooleanExpression[]) neAddrs.toArray())
    ))
```

**Comment by christophstrobl** [comment]
any update on this?
Trying to solve [DATAMONGO-1810](https://jira.spring.io/browse/DATAMONGO-1810) in [Spring Data MongoDB](https://github.com/spring-projects/spring-data-mongodb) I'm struggling with this very same issue. Actually the values used for constructing the `$in` operation should be run through `convert`, which would give us the data required to perform the conversion (eg. from a plain `String` into an `ObjectId`) based on the metadata.

**Comment by philippeboyd** [comment]
Waiting on an update on this case as well...

After doing some digging, I've found out that that it all starts with Spring's `SpringDataMongodbSerializer.asDBObject(@Nullable String key, @Nullable Object value)`.

There's a check for and `_id` key

```java
if (ID_KEY.equals(key)) {
	DBObject superIdValue = super.asDBObject(key, value);
	Document mappedIdValue = mapper.getMappedObject((BasicDBObject) superIdValue, Optional.empty());
	return (DBObject) JSON.parse(mappedIdValue.toJson());
}
```

When we go down the rabbit hole on `mapper.getMappedObject(...)` we'll get to Spring's `QueryMapper.getMappedValue(Field documentField, Object value)` which will convert the IDs pass as value : `ids.add(convertId(id));`.

So for example a Predicate of 
```
someCollection.id in [5a2843b9b5fa9a85201e06cd, fake_id, 5a2843b9b5fa9a85201e06cf]
```
will become 
```
{ "_id" : { "$in" : [ { "$oid" : "5a2843b9b5fa9a85201e06cd"} , "fake_id" , { "$oid" : "5a2843b9b5fa9a85201e06cf"}]}}
```
which is what we want. (those representation are from `toString()`)

However, for DBRef with a Predicate of 
```
someCollection.user in [5a2843b6b5fa9a85201e06c6, fake_id]
```
we will get
```
{ "user" : { "$in" : [ "5a2843b6b5fa9a85201e06c6" , "fake_id"]}}```
because the key `user` is not an `ID_KEY` aka `_id`.

My solution was to somehow extend `SpringDataMongodbSerializer` and override `asDBObject(@Nullable String key, @Nullable Object value)` by adding another condition to be able to go down the rabbit hole and convert those IDs to ObjectIDs but `SpringDataMongodbSerializer` is package protected...

What @christophstrobl is suggesting (`the values used for constructing the $in operation should be run through convert`) is a good start but it still won't get pass the condition in `SpringDataMongodbSerializer.asDBObject(@Nullable String key, @Nullable Object value)`

**Comment by simonered** [comment]
Any news after 1.5 years???

**Comment by christophstrobl** [comment]
@simonered we've been working on this on the SpringData side and have been able to resolve [DATAMONGO-1810](https://jira.spring.io/browse/DATAMONGO-1810) via [DATAMONGO-1848](https://jira.spring.io/browse/DATAMONGO-1848) maintining a `MongodbDocumentSerializer` that is a bit more open and works with `org.bson.Document`.

**Comment by simonered** [comment]
@christophstrobl I saw your solution, but it's on 2.1 version and I'm curently using 1.10.13

**Comment by christophstrobl** [comment]
sorry to say this, but I'm afraid we cannot back port it to the 1.x line - if there's any movement on the issue here we'd be more than happy to do what we can on our side to ship a fix.

**Comment by simonered** [comment]
Is there any workaround?

**Comment by christophstrobl** [comment]
I know none right of the top of my head - we tried a while ago (see: [issue branch  for DATAMONGO-1810](https://github.com/spring-projects/spring-data-mongodb/compare/issue/DATAMONGO-1810)) but it turned out to be insufficient and work only under certain circumstances. If you happen to find a solution a PR would be warmly welcome.
