### ISSUE TITLE
Generated HQL for a Count Query with multiple Group By columns not producing valid SQL for MSSQL 

### ISSUE THREAD

**Issue by pointwisefixed** [querydsl/querydsl#2134]
Related to #1472 

I think the fix introduced a bug. When I do aggregations on any column and add a new group by. It will generate a count query HQL that looks like this:
```
select count(distinct col1, col2)
// where col1 and col2 are the group by columns.
```
In MSSQL it will throw an exception as the generated SQL from the HQL is not valid SQL for MSSQL. 

The issue has been touched on this hibernate issue:

https://hibernate.atlassian.net/browse/HHH-11042?page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel&showAll=true

With the result being to implement a dialect specific sql function for sql server that would create valid sql for this use case. The resulting sql would have the following format:

```
count(distinct coalesce(nullif(coalesce(col1 || '', '\0'), ''), '\01') || '\0' || coalesce(nullif(coalesce(col2 || '', '\0'), ''), '\02'))
```

Is there any way to do this right now in querydsl (i.e. add your own override count function to the count query)? What do you guys think a good workaround would be?

Thanks,

Gary

**Comment by Maze-fr** [comment]
I had the same issue while doing a `count` on a `select distinct` query.
It is not M$SQL limitation, it is SQL language limitation.
Both `count` and `distinct` are aggregation functions, and you can't aggregate an aggregated result.

The only way I found is to do a `select count(*) from (select distinct`, but JPA specifications doesn't allow it.
So I tried using the `SQLQueryFactory` instead of `JPAQueryFactory`, but I didn't manage to "translate" the JPA generated query into a proper SQL query. If anyone has a hint, I would be glad to read it.

So... the workaround I used is to create a SQL view  with my `select distinct` and I easily use it with JPA.

**Comment by jaumzera** [comment]
Facing the same around here. 
I had to create a count query distincting columns to simulate a count.

**Comment by syedammarzia** [comment]
Facing this issue. It is a pretty basic issue and should be fixed. Is there any timeline for this? It seems like it is already long overdue.

**Comment by cbesangeeth** [comment]
I have a scenario to fetch count of following SQL. 

`select count( distinct col1, col2) from table`

**How do i do it using queryDsl JPAQuery?**

Currently i have framed like this, however i don't have option to do counting DISTINCT over multiple columns.
```
jpaQuery
      .from(qTable)
      .where(wherePredicate).
      .select(qTable.col1, qTable.col2)
      .fetchCount();
```
Any suggestions?

**Comment by jaumzera** [comment]
Have you tried the following?

jpaQuery
      .from(qTable)
      .where(wherePredicate).
      .select(qTable.col1, qTable.col2)**.distinct()**
      .fetchCount();

**Comment by cbesangeeth** [comment]
@jaumzera Yes, I had tried your query, however i'm getting SQL queries as
`select count(distinct table.id) from table`
