### ISSUE TITLE
NullPointerException while initialise QueryDsl Model

### ISSUE THREAD

**Issue by hammadirshad** [querydsl/querydsl#2139]
I create query DSL model with 'com.querydsl.apt.jpa.JPAAnnotationProcessor'

    l1: @Generated("com.querydsl.codegen.EntitySerializer")
    l2: public class QAbstractRuleModel extends EntityPathBase<AbstractRuleModel> {
    l3:     private static final PathInits INITS = PathInits.DIRECT2;
    l4:     public static final QAbstractRuleModel abstractRuleModel = new QAbstractRuleModel("abstractRuleModel"); 
    l5: 
    l6:     public QAbstractRuleModel(String variable) {
    l7:        this(AbstractRuleModel.class, forVariable(variable), INITS);
    l8      }
    l9:}

and I use IntelliJ 2017 to reformat my code. IntelliJ rearrange static initialization and swap
l2 with l3 and constructor of **QAbstractRuleModel** depend on **INITS** and **INITS** initialized 
after **QAbstractRuleModel** constructor which cause NullPointerException on line l7.
as per my understanding **INITS** must be initialized inside a constructor or pass PathInits.DIRECT2 at line l7.

**Comment by Shredder121** [comment]
> as per my understanding INITS must be initialized inside a constructor

It's unfortunately static, it's basically to not inline multiple references to `PathInits.[something]`.

> or pass PathInits.DIRECT2 at line l7

We prefer determining which `PathInits` to pick (or create) only once, and at the top of the file.
Otherwise we would need to inline the determining part into every call, and if we need to create it, then we'd create the same thing multiple times per file.

The quickest way is to not reformat the code, since it's generated every time anyway, and we don't test against every ordering available.
