### ISSUE TITLE
Spatial queries with web mercator coordinates do not work

### ISSUE THREAD

**Issue by mpschaeuble** [querydsl/querydsl#2144]
querydsl-spatial references a really old geolatte-geom version (0.13), which uses a buggy CRS definition file. This leads to the fact that no queries can be made using web mercator coordinates. 

This bug has been fixed with geolatte-geom version 1.0.3 (https://github.com/GeoLatte/geolatte-geom/issues/41). Please update to the latest geolatte-geom version.

**Comment by cnsgithub** [comment]
In the meantime geolatte-geom-1.2.0 is out.  I cannot accept any longer getting stuck at versions that are almost four years now. Please, please, please querydsl: release a new version as soon as possible, or users won't stay with you any longer and will search for querydsl alternatives. That would be a shame, since querydsl had been such a cool project for years.

**Comment by cnsgithub** [comment]
However, at least updating geolatte-geom to 0.15 should not break compatibility (albeit not yet tested).
