### ISSUE TITLE
Alternative for  "Maven APT plugin" in Gradle

### ISSUE THREAD

**Issue by Ziemowit** [querydsl/querydsl#2231]
Could you provide in documentation an alternative for Maven APT plugin which will be working with Gradle?

**Comment by Shredder121** [comment]
You can use javac apt instead.
Is that not in the documentation?
We provide jars with META-INF/services files, in the querydsl-apt:${classifier} artifacts

**Comment by reegnz** [comment]
Since gradle 4.3 adding an annotation processor to your gradle project became much simpler:
https://docs.gradle.org/4.3/release-notes.html#specify-output-directory-for-source-files-generated-by-annotation-processor
* You just need to define the processor as a compileOnly dependency
* You need to define compileJava.options.annotationProcessorGeneratedSourcesDirectory

Example build.gradle:
```
apply plugin: java
dependencies {
    compileOnly 'com.querydsl:querydsl-apt:4.1.4:jpa'
}
compileJava.options.annotationProcessorGeneratedSourcesDirectory = file("${buildDir}/generated/source/apt")
```

**Comment by reegnz** [comment]
FYI pre-4.3 you had to do more hacks to override the generated sources directory (pass custom args to javac).

**Comment by Ziemowit** [comment]
Thank you @reegnz!
It is sth what I have been searching for!

@Shredder121 I just was asking is there possibility to add a sub topic in documentation for "Gradle Integration" in the same way as it is done for Ant & Maven integration.

But it was just the question. You can close the issue like "we are not going to extend documentation by this information" :)

**Comment by timowest** [comment]
Feel free to provide a PR for the documation update.

**Comment by Keerthana-Sritharan** [comment]
jn
