### ISSUE TITLE
Checkstile rule not consistent across main and test source sets

### ISSUE THREAD

**Issue by reegnz** [querydsl/querydsl#2243]
In #2037 I encountered the issue:
Checkstyle didn't warn about indentation being 8 spaces instead of 4.

Checkstyle indentation rules should apply to test sources as well.

**Comment by Shredder121** [comment]
Yeah, thanks for opening, I'd started already a bit.

**Comment by Shredder121** [comment]
Unfortunately we cannot use [IndentationCheck's forceStrictCondition][IndentCheck], which is mainly what this is about.

It complains about various places, to use less indenting (since 'continuation' is either active, or not; there's no level of continuation).

<details>
<summary>Example where it wants the second wrapping to be less indented (click me)</summary>

https://github.com/querydsl/querydsl/blob/2468042ed7c20b269d85edafd4d7fe790a2dd6e3/querydsl-core/src/test/java/com/querydsl/core/group/GroupByIterateTest.java#L256-L258

</details>

But indentation in general can be added to the checkstyle configuration.

[IndentCheck]: http://checkstyle.sourceforge.net/config_misc.html#Indentation

**Comment by Shredder121** [comment]
Just a heads-up btw.
Want to also focus on a few non-development related issues.
