### ISSUE TITLE
Wrong type returned when using SQLExpressions.date with LocalDateTime

### ISSUE THREAD

**Issue by F43nd1r** [querydsl/querydsl#2319]
```java
QReport report = QReport.report;
DateTimePath<LocalDateTime> date = report.date;
DateExpression<LocalDateTime> dateExpression = SQLExpressions.date(date);
LocalDateTime localDateTime = new JPAQuery<>(entityManager).from(report).select(dateExpression).fetchFirst();
```

This code compiles, but throws a ClassCastException at runtime, because fetchFirst returns a `java.sql.Date`, not a `java.time.LocalDateTime`

QueryDsl 4.2.1
Hibernate 5.2.17.Final
MariaDB 10.1.33

**Comment by jwgmeligmeyling** [comment]
The `SQLExpressions` are not meant to be used with JPA expressions. This is the root of problems like these. `SQLExpressions` are for SQL queries, for JPA queries you should use `JPAExpressions`. Some generic expressions that work on "most" query languages live in `Expressions`. You'll notice that `JPAExpressions` does not include a `DATE` function. This is because `DATE` is not an officially supported function by the JPA specification.

`SQLExpressions.date` creates a `DATE` function expression. Hibernate happens to have a `DATE` function that returns a `java.sql.Date`. If you want Hibernate to return a LocalDateTime instead, you need to register a custom function.

```java
public class DateAddIntervalMetadataBuilderInitializer
        implements MetadataBuilderInitializer {
    @Override
    public void contribute(MetadataBuilder metadataBuilder,
            StandardServiceRegistry serviceRegistry) {
        metadataBuilder.applySqlFunction("DATE",
            new SQLFunctionTemplate(LocalDateTimeType.INSTANCE,
                "DATE(?1)"));
    }
}
```

You would also need to put the name of the class in a JAR resource file called `META-INF/services/org.hibernate.boot.spi.MetadataBuilderInitializer`.

**Comment by F43nd1r** [comment]
Thanks for the explanation and workaround.
