### ISSUE TITLE
QueryDSL fetching set collection in SELECT projection

### ISSUE THREAD

**Issue by vmasule** [querydsl/querydsl#2371]
I have a nested JPA entity structure which looks something like below 

    @Entity
    public class Applicant {
    
      @OneToMany()
      private Set<Address> addresses;

      // other applicant fields
    
    }

    @Entity
    public class Address {
    
      private String houseName;

      private String houseNumber;

      private String postcode;
    
    }

And I have trying to get applicant details with set of address by following query but it returns 'Type Mismatch'

    
    private static final ConstructorExpression<AddressEntity> qAddresses = QAddressEntity.create(
            qAddressEntity.houseName, qAddressEntity.houseNumber, qAddressEntity.postcode);

    @Test
    public void shouldTestAddressWithProjection() {
        JPAQuery<ApplicationEntity> jpaQuery = new JPAQuery<>(entityManager);
        QueryResults<ApplicantEntity> queryResults = jpaQuery.select(
                Projections.bean(ApplicantEntity.class, qApplicantEntity.forename, qApplicantEntity.surname,
                        GroupBy.set(qAddresses).as("addresses")))
                .from(qApplicantEntity)
                .leftJoin(qApplicantEntity.addresses, qAddressEntity)
                .where(qApplicantEntity.forename.startsWithIgnoreCase("Nikki"))
                .fetchResults();

    }

I know of the fact that I can use `.transform()` and it works with is but I loose the pagination that comes with `fetchResults()`. Please let me know the solution for this issue.

**Comment by vmasule** [comment]
Hi,

Any updated on this please.

**Comment by bobocu** [comment]
did you find any solution on this ?

**Comment by jwgmeligmeyling** [comment]
`GroupBy.set` groups in memory, not in SQL, so the count query would return the wrong count anyway. GroupBy expressions can not be used with `fetchResults` and I would be surprised if they work properly with `select()` instead of `transform()` at all.

Also, `fetchResults` is deprecated for `JPAQuery` because the count query can't be reliably generated in JPA.

**Comment by garfieldcoked** [comment]
Hi @jwgmeligmeyling , this ticket was closed but I didn't see any feedback on the OP's actual issue of using Projection with set, there is Projection.list but no Projection.set. Is there a way to accomplish this?

Thank you.

**Comment by jwgmeligmeyling** [comment]
The OP tries to use `Projections.bean` with a nested `GroupBy.set` in a selection using `fetchResults()`. `GroupBy` expressions are not supported as selection, only as result transformation. And by definition cannot be used together with `fetchResults()`.

The OP doesn't mention `Projections.list` at all nor does he mention `Projections.set` - which indeed does not exists.

**Comment by garfieldcoked** [comment]
Hi @jwgmeligmeyling, thank you for your response. I may be wrong but the OP might have tried the Groupby.set because he's trying to do a projection for the OneToMany field "addresses" which is a set and not a list. It's also the name of this issue "fetching set collection in SELECT projection". So the groupby/transform is not the intention but just something tried because the way to achieve this is not clear. Well at least for me, I have a similar setup and facing a similar issue because there is no Projections.set, I tried Projections.list but as expected failed.

How would one do a bean or field projection to add the set of addresses? 

Thanks in advance

**Comment by alohaaloha** [comment]
@garfieldcoked were you able to find solution?

**Comment by danztensai** [comment]
Having the same problem , are there any solution for this??
