### ISSUE TITLE
StringExpression.containsIgnoreCase too slow in PostgreSQL

### ISSUE THREAD

**Issue by suryamukerjee** [querydsl/querydsl#2381]
StringExpression.containsIgnoreCase too slow in PostgreSQL because it converts into lower(column_name) like '%value%' escape '!'. 

PostgreSQL provides the keyword 'ilike' for like by ignore case. I did not find any equivalent StringExpression method for building a query with 'ilike' in the where clause.

Could you please provide a workaround or a fix?

I am using Querydsl from my Spring Boot application with spring boot's starter JPA

Thanks

**Comment by jwgmeligmeyling** [comment]
The problem is that `ilike` is dialect specific. As a result there is no way to represent it in JPQL, the query language for JPA that QueryDSL uses to execute a query through Hibernate (most likely used in your Spring Boot starter).

First you'd have to create a function that is able to render the desired SQL for PostgreSQL:

```
public class ILikeMetadataBuilderInitializer
        implements MetadataBuilderInitializer {
    @Override
    public void contribute(MetadataBuilder metadataBuilder,
            StandardServiceRegistry serviceRegistry) {
        metadataBuilder.applySqlFunction("ilike",
            new SQLFunctionTemplate(BooleanType.INSTANCE,
                "?1 ilike ?2"));
    }
}
```

You would also need to put the name of the class in a JAR resource file called `META-INF/services/org.hibernate.boot.spi.MetadataBuilderInitializer`.

Then you have to register the template in a subclass of `JPQLTemplates`:

```java
public class MyTemplates extends JPQLTemplates {

    public MyTemplates() {
        add(Ops.STRING_CONTAINS_IC, "ILIKE(?1, ?2)");
    }
    
}
```

Next you have to associate your query with an instance of `MyTemplates`, i.e. `new JPAQuery(entityManager, new MyTemplates())`.

As a result, your `StringExpression.containsIgnoreCase` will render the desired expression.
