### ISSUE TITLE
Please update to current JTS version (org.locationtech.jts:jts-core:1.16.0)

### ISSUE THREAD

**Issue by tucek** [querydsl/querydsl#2404]
Please exchange the old jts dependency with the maintained successor:
https://mvnrepository.com/artifact/org.locationtech.jts/jts-core/1.16.0

**Comment by Shredder121** [comment]
Sounds like a good plan,thanks!

**Comment by tucek** [comment]
Hibernate spatial 5.4 depends on org.geolatte:geolatte-geom:1.4.0 which in turn depends on the org.locationtech.jts:jts-core:1.16.0

So currently the latest version of querydsl aptial is incompatible with the latest version of hibernate.

**Comment by mstahv** [comment]
Tried a quick upgrade in PR #2418. All but PolyHedralSurface was simple find and replace. Any ideas how to fix those?

**Comment by mstahv** [comment]
I tried to get little further in a separate branch https://github.com/mstahv/querydsl/tree/feature/geolatte-and-jtsupgrade-removed-polyhedral by just removing the PolyHedralSurface stuff. It appears there is a lot to do still in sql-spatial module 😥

**Comment by mstahv** [comment]
I haven't had time to work on this lately. Summer cottage project disturbing my OSS contributions 😥 I hope somebody can take over my PR.

**Comment by idosal** [comment]
If anyone would like to take over this PR I'll be happy to merge it. Please note that spatial probably won't be in active development by the team going forward.

**Comment by ddcruver** [comment]
@mstahv, what more needs to be done on your branch?  

It makes sense for you to just remove the PolyHedralSurface components because Goelatte removed these in https://github.com/GeoLatte/geolatte-geom/commit/edc901f4f9618e6dcb92f69167f4a92a76a67cc7.

Also to point out this was removed over 6 years ago. I don't think it is coming back.  The comment states they reworked their position based geometries, so maybe after these changes it this model was no longer needed.

@idosal do you know anything he is missing on his branch?

**Comment by jwgmeligmeyling** [comment]
The SQL module stuff apparently..

>  It appears there is a lot to do still in sql-spatial module

**Comment by mstahv** [comment]
Yep, I think the only easy way out is to remove polyhedral features and related tests at this point. IIRC (it has been a while), I found no way how to support them now. 

I'd be honoured if somebody would continue my work on this. I'd love to upgrade one of my examples to newer Hibernate, but I probably don't have time for this before the autumn due to my building project.

**Comment by jwgmeligmeyling** [comment]
I think everyones onboard with removing  polyhedral features. Are there any other test failures in the SQL module that you remember?

If no one else picks it up in the mean time, I am willing to work on it but I first have to finish up some of my other pending OSS contributions.

**Comment by ddcruver** [comment]
I removed some more instances of polyhedral features and merged in master on my fork.  When I ran the test though there was failures, oddly in parts that didn't relate to geospatial objects.
