### ISSUE TITLE
Querying Collections fails when upgrading JDK

### ISSUE THREAD

**Issue by emazv72** [querydsl/querydsl#2455]
Querying a collection works on JDK 1.8

			FilterDescriptor qFilter = alias(FilterDescriptor.class, "filter");
			List<FilterDescriptor> filters;
                         ...  			
			from($(qFilter), filters).where($(qFilter.getField())
						.eq("USER_ID"))
						.singleResult($(qFilter.getValue()));

but fails on JDK11 with the following exception:

> 
> java.lang.RuntimeException: java.lang.UnsupportedOperationException

>	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:163) 
com.mysema.codegen.JDKEvaluatorFactory.compile(JDKEvaluatorFactory.java:73) ~[codegen-0.6.8.jar:?]
> Caused by: java.lang.UnsupportedOperationException
	at com.mysema.codegen.MemFileManager.getJavaFileForInput(MemFileManager.java:91) ~[codegen-0.6.8.jar:?]

It seems getJavaFileForInput actually throws an exception.

querydsl version is 3.7.4

It might be linked to this issue:
https://github.com/cglib/cglib/issues/129

Is querydsl locked in with JDK version?

**Comment by marceloverdijk** [comment]
Is querydsl codegen supported on JDK 11 or even JDK 15?

**Comment by jwgmeligmeyling** [comment]
QueryDSL 3.7.4 is very old no longer maintained. QueryDSL 4.4.0 supports Java 8 and Java 9+ with some modifications. QueryDSL Collections 4.4.0 uses a really old cglib version and only works when using a JDK and not when using a JRE. QueryDSL 5 will improve support for Java 9+ but is currrently unreleased.

**Comment by marceloverdijk** [comment]
Hi @jwgmeligmeyling 
I’m using Querydsl Collections 4.4 with Spring Boot Data Key Value (or at least trying).
You mean I could try to use another version of cglib in my project, or is there at the moment no real solution using Querydsl Collections from JDK 11 onwards until Querydsl 5 is released?

**Comment by jwgmeligmeyling** [comment]
JDK 11 is pretty much unsupported for QueryDSL 4.4.x but most users have been able to get it to work with minor tweaks like updating a couple dependencies.

QueryDSL 5.x compiles and tests against JDK 11 just fine. I am not sure about JDK 15 yet, it simply hasn't been tested, but as the changes between 11 and 15 are much less drastic than between 8 and 9 I suppose it will be fine (except maybe codegen that might struggle a little with Records).

**Comment by marceloverdijk** [comment]
Thanks for the feedback @jwgmeligmeyling !

**Comment by viktorzub** [comment]
@jwgmeligmeyling regarding minor tweaks like updating a couple dependencies., if you know which one, can you provide some info? Because i can't use Collections due to the same error, I use Java 11 + Spring Boot 2.3.9 and tried with QueryDSL 4.2.2, 4.4.0, 4.3.1, Whithout success.  Aslo i use apt-maven-plugin for annotation processing.

**Comment by jwgmeligmeyling** [comment]
For Java 11 you'll need Querydsl 5.0.0.M1 minimally.

**Comment by viktorzub** [comment]
@jwgmeligmeyling for java 11 i receive another 
Compilation of public class Q_0911015504_1275614662_1275614662_1195259493_01114099497 failed  exeption,/Q_0911015504_1275614662_1275614662_1195259493_01114099497.java:3: error: package com.mypackage.dto does not exist, so i suppose in some reason compilator doesn't see packages

Mb you have working pom file for java 11 and qdsl?

**Comment by jwgmeligmeyling** [comment]
Querydsl compiles against Java 11 😉  So any example in the Querydsl project is a working example.

Perhaps your combining old and new versions for `querydsl-core`, querydsl-codegen`, `querydsl-collections`, `querydsl-jpa`, and/or `querydsl-apt`?

**Comment by viktorzub** [comment]
@jwgmeligmeyling  i use only querydsl-jpa, also same version of querydsl-apt. Q calsses are generated fine. The problem is - build CollQueryFactory.from(some, some).where(predicate).fetch() i receive exeption that i mentioned above. If i use it without where, all works fine. Also i use lightweight tomcat, is it can be issue?

**Comment by jwgmeligmeyling** [comment]
Could you share the full stacktrace and the output of mvn dependency:tree?

**Comment by viktorzub** [comment]
[Trace.log](https://github.com/querydsl/querydsl/files/6716714/Trace.log) - i hope this is fine for you?
Regarding "classpath mode" what does it mean ? I use embeded tomcat, jar instead of war builded.

mvn dependency tree is too big but, [INFO] +- cglib:cglib:jar:3.3.0:compile
[INFO] |  +- com.querydsl:querydsl-jpa:jar:5.0.0.M1:compile
[INFO] |  |  \- com.querydsl:querydsl-core:jar:5.0.0.M1:compile
[INFO] |  |     \- com.mysema.commons:mysema-commons-lang:jar:0.2.4:compile
[INFO] |  +- com.querydsl:querydsl-collections:jar:5.0.0.M1:compile
[INFO] |  |  +- com.querydsl:querydsl-codegen:jar:5.0.0.M1:compile
[INFO] |  |  |  +- com.querydsl:codegen-utils:jar:5.0.0.M1:compile
[INFO] |  |  |  |  \- org.eclipse.jdt:ecj:jar:3.25.0:compile
[INFO] |  |  |  +- javax.inject:javax.inject:jar:1:compile
[INFO] |  |  |  \- io.github.classgraph:classgraph:jar:4.8.108:compile
[INFO] |  |  \- com.querydsl:querydsl-apt:jar:5.0.0.M1:compile
[INFO] |  +- com.github.vineey:rsql-querydsl-all:jar:2.0.0.RELEASE:compile
[INFO] |  |  +- com.github.vineey:rsql-api-all:jar:2.0.0.RELEASE:compile
[INFO] |  |  |  +- com.github.vineey:rsql-api-core:jar:2.0.0.RELEASE:compile
[INFO] |  |  |  +- com.github.vineey:rsql-api-select:jar:2.0.0.RELEASE:compile
[INFO] |  |  |  +- com.github.vineey:rsql-api-filter:jar:2.0.0.RELEASE:compile
[INFO] |  |  |  +- com.github.vineey:rsql-api-sort:jar:2.0.0.RELEASE:compile
[INFO] |  |  |  \- com.github.vineey:rsql-api-page:jar:2.0.0.RELEASE:compile
[INFO] |  |  +- com.github.vineey:rsql-querydsl-page:jar:2.0.0.RELEASE:compile
[INFO] |  |  +- com.github.vineey:rsql-querydsl-select:jar:2.0.0.RELEASE:compile
[INFO] |  |  +- com.github.vineey:rsql-querydsl-filter:jar:2.0.0.RELEASE:compile
[INFO] |  |  \- com.github.vineey:rsql-querydsl-sort:jar:2.0.0.RELEASE:compile
[INFO] |  |  +- org.springframework.data:spring-data-jpa:jar:2.3.9.RELEASE:compile

**Comment by jwgmeligmeyling** [comment]
`Compilation of public class Q_0911015504_1275614662_1275614662_1195259493_01114099497 failed exeption,/Q_0911015504_1275614662_1275614662_1195259493_01114099497.java:3: error: package com.mypackage.dto does not exist, so i suppose in some reason compilator doesn't see packages` is caused by another issue than the issue reported here.

Unfortunately the issue is hard to reproduce without more context. Perhaps you could try recreating the issue in the Querydsl integration test domain? Existing tests for querydsl collections can be found in: https://github.com/querydsl/querydsl/tree/master/querydsl-collections/src/test/java/com/querydsl/collections
