### ISSUE TITLE
BooleanPath .not()  NoViableAltException: unexpected token: not

### ISSUE THREAD

**Issue by WellJay** [querydsl/querydsl#2539]
![image](https://user-images.githubusercontent.com/7018973/76184081-82616180-6205-11ea-8ca9-3428f5ec353e.png)

java.lang.IllegalArgumentException: org.hibernate.hql.internal.ast.QuerySyntaxException: unexpected token: not near line 2, column 24 [update com.gzlh.xiaolian.news.entity.TopBanner topBanner
set topBanner.banned = not topBanner.banned

**Comment by jwgmeligmeyling** [comment]
This simply seems to mean that `SET banned = NOT banned`  is not valid in your dialect. I am not sure if it will be valid in any SQL dialect, I would have to test that. I think you can work around the issue by extending `SQLTemplates` so that it renders `! <expression>` instead of `NOT <expression>`. Alternatively, you could create a template expression: `Expressions.booleanTemplate("! {0}", Q_TOP_BANNER.banned)`.

Which SQL dialect are you using?

**Comment by WellJay** [comment]
MySQL55Dialect
com.mysql.cj.jdbc.Driver
