### ISSUE TITLE
QueryDSL generate SQL statement incorrect when applying alias on column name.

### ISSUE THREAD

**Issue by datntvn** [querydsl/querydsl#2558]
I created a query as below

`JPAQueryFactory queryFactory = new JPAQueryFactory(entityManager);`

```
        queryFactory
                .select(Projections.fields(MinimumStockPlanning.class,
                        minStockPlanning.minimumStockId.articleId.as("articleId"),
                        ExpressionUtils.as(
                                minStockPlanning.minQuantity,
                                "minQuantity")
                ))
                .from(minStockPlanning)
                .fetch();

```
And from the log, here is the generated SQL
```
 select minimumsto0_.article_id as col_0_0_, minimumsto0_.min_quantity as col_1_0_ from MINIMUM_STOCK_PLANNING minimumsto0_
```
The problem is that, column name alias does not work.

When I tried to see the QueryDSL generate (i.e: not the SQL statement), then here is the output:

```
select minimumStockPlanning.minimumStockId.articleId as articleId, minimumStockPlanning.minQuantity as minQuantity
from MinimumStockPlanning minimumStockPlanning
```
It seems like, QueryDSL generate alias ok, but the SQL statement is in correct.

I'm using spring-boot, with below libraries:
```
spring-boot-starter-parent: 2.0.1.RELEASE
querydsl.version : 4.3.1
spring-boot-starter-data-jpa: 2.2.6.RELEASE
```

**Comment by datntvn** [comment]
I wonder whether this issue is the same as below issue:

[https://github.com/querydsl/querydsl/issues/1934](https://github.com/querydsl/querydsl/issues/1934)

But, if these 2 issues are the same.
Then, solution of updating Hibernate version is impossible in my case.
Because I do not use Hibernate directly, instead, I only use spring-jpa.

**Comment by jwgmeligmeyling** [comment]
Aliases are only used in the JPQL query.  The actual aliases used in the SQL query are determined by your ORM provider. Hibernate for example chooses not to use the aliases from the JPQL query, but instead generates its own. That is necessary because a single alias in a JPQL query can involve a dozen of columns in the underlying SQL query, i.e. when projecting entities, embeddables or compound types.

So this is not something we have control over. If you want to control the produced SQL, you should write a SQL query, not a JPA/JPQL query.

**Comment by datntvn** [comment]
Thank you for your feedback.
