### ISSUE TITLE
dayOfWeek doesn't work on Oracle

### ISSUE THREAD

**Issue by vertti** [querydsl/querydsl#260]
Using `DateExpression.dayOfWeek()` causes JPQL query similar to 

```
where dayofweek(issue.issueDate) in (?1) 
```

but dayofweek is not a function supported by Oracle. Querydsl could maybe translate this to something horrible like

```
 cast (to_char(issuedate, 'D') as numeric) 
```

with Oracle?

**Comment by philip-tbits** [comment]
Hi,

So I followed Timo's guide and it worked fine. But then I had to change NLS_TERRITORY to have Saturday as first day of week and something weird happened.

I had created dayofweek function in extended oracle dialect, and called that in the projection. 
`new CaseBuilder().when(Expressions.numberTemplate(Integer.class, "function('dayofweek', {0})", sale.dt).eq(1)).then(sale.amt).otherwise(BigDecimal.ZERO).sum()`

The raw sql generated in logs showed output correctly, Saturday data was mapped to weekday 1 as confirmed by running it directly in sqlplus; but the logs in my console showed extracted value with different weekday 1, it showed data for Monday(old NLS_TERRITORY ).

So somehow the dayofweek translation in spring/hibernate/querydsl is not taking into account the prevalent NLS_TERRITORY settings.

Any thoughts & resolutions?

I use Spring 4.3.6.RELEASE, Hibernate 5.2.8.Final, QueryDsl 4.1.3, Oracle10g

Thanks!
