### ISSUE TITLE
QueryDsl doesn't generate the correct type

### ISSUE THREAD

**Issue by RyK-eR** [querydsl/querydsl#2606]
QueryDsl don't generate the correct type in QClass. It generate me a NumberPath instead of EnumPath.

<img width="675" alt="Screenshot 2020-06-01 at 21 22 16" src="https://user-images.githubusercontent.com/52129860/83445952-2eee6080-a44e-11ea-9c8f-c5dd51edd117.png">

<img width="681" alt="Screenshot 2020-06-01 at 21 22 31" src="https://user-images.githubusercontent.com/52129860/83445967-34e44180-a44e-11ea-8f19-07dcb4c788dc.png">

**Comment by jwgmeligmeyling** [comment]
It must be the ordinal that makes QueryDSL think this should map a NumberPath. While to some extent that is useful, because numeric operations can in fact be used on enum paths that are mapped by an ordinal, obviously `Enums` do not implement  `Numbers` leading to all the errors occurring during compilation. Obviously this should not occur.

Could be related to #1559, another issue where the generic bound was misinterpreted during codegen.
