### ISSUE TITLE
JPA: join subquery

### ISSUE THREAD

**Issue by wangyedong66** [querydsl/querydsl#2607]
In JPA:
sql:
select A.* from A join (select aid from B group by aid) b on b.aid=A.id;
How to do?

**Comment by jwgmeligmeyling** [comment]
This is not possible in JPQL, because subqueries are only allowed in the SELECT, WHERE and HAVING clauses. As a result, QueryDSL doesn't support them in JPA queries. QueryDSL does support subquery joins in SQL queries (but that's of no use for JPA).

Blaze-Persistence is an extension for JPA. Their flavour of JPQL, JPQL,Next, does support joining subqueries through common table expressions. There is a QueryDSL integration described [here](https://persistence.blazebit.com/documentation/1.5/core/manual/en_US/index.html#querydsl-integration), Using that extension, you could write;

```java
QRecursiveEntity recursiveEntity = new QRecursiveEntity("t");

List<RecursiveEntity> fetch = new BlazeJPAQuery<>(entityManager, cbf)
    .select(recursiveEntity)
    .from(select(recursiveEntity)
        .from(recursiveEntity)
        .where(recursiveEntity.parent.name.eq("root1"))
        .orderBy(recursiveEntity.name.asc())
        .limit(1L), recursiveEntity)
    .fetch();
```

This API is analog to subquery joins in `querydsl-sql`.

The Blaze-Persistence QueryDSL integration even supports lateral joins (joins that reference outer query variables, also known as `CROSS APPLY`):

```java
QRecursiveEntity t = new QRecursiveEntity("t");
QRecursiveEntity subT = new QRecursiveEntity("subT");
QRecursiveEntity subT2 = new QRecursiveEntity("subT2");

List<Tuple> fetch = new BlazeJPAQuery<>(entityManager, cbf)
    .select(t, subT2)
    .from(t)
    .leftJoin(select(subT).from(t.children, subT).orderBy(subT.id.asc()).limit(1), subT2)
    .lateral()
    .fetch();
```

Disclaimer: I am a QueryDSL and Blaze-Persistence contributor.

**Comment by GauravRatnawat** [comment]
QueryDsl does not support subQuery in join but you can achieve this via following way: 

Map a View or SQL query to JPA entity:

`import lombok.Getter;
import lombok.Setter;
import org.hibernate.annotations.Subselect;
import org.hibernate.annotations.Synchronize;

import javax.persistence.Entity;
import javax.persistence.Id;

@Entity
@Getter
@Setter
@Subselect("select aid from B group by aid")
@Synchronize("B")
public class BGroupByAid {

    @Id
    private Integer aId;
}`

then use the equivalent QueryDSl entity in the class just like the regular entity:
`
JPAQuery<QAsset> query = new JPAQuery<>(entityManager);  
QBGroupByAid bGroupById = QBGroupByAid.bGroupByAid;

 List<A> tupleOfAssets =
            query.select(A)
        .from(A).innerJoin(bGroupById).on(bGroupById.aId.eq(A.aId))
        .fetchResults()
        .getResults();
        `
