### ISSUE TITLE
Documentation is old

### ISSUE THREAD

**Issue by d-schmidt** [querydsl/querydsl#2631]
I'm struggeling to find any current docs.

http://www.querydsl.com/ and https://twitter.com/querydsl are stuck in 2016 version 4.1.3
The wiki on Github is almost empty.
I can't even find a changelog. What happened in 4.2.2 and 4.3.1?

I want to know how to tell QueryDSL to generate JDK8 Instants and not old Timestamps from DB.

**Comment by jwgmeligmeyling** [comment]
QueryDSL SQL was never updated for Java 8. In fact, project was not updated for years and only recently started to get picked up again. I am one of the active contributors now, but most of my work revolves around Querydsl JPA as frankly, I am not using any of the other modules.

QueryDSL JPA supports the Java 8 date/times just fine. Which Querydsl module are you using?

**Comment by d-schmidt** [comment]
Yes, this particular project uses querydsl-sql.

Still, did anybody update any docs or change logs.

**Comment by jwgmeligmeyling** [comment]
We did update the documentation, but we only recently got access to the website hosting, so we have to reupload it.

As far as QueryDSL SQL goes, the documentation for 4.1.3 is still accurate though.

**Comment by MatthewBerk** [comment]
@jwgmeligmeyling  Would there be a benefit to updating QueryDSL SQL to Java 8? or do you think focus should be on QueryDSL JPA?

**Comment by jwgmeligmeyling** [comment]
@MatthewBerk  QueryDSL 5.x will require Java 8 minimally, and also support Java 9+. This includes `querydsl-sql`. The benefits for `querydsl-sql` will be that we finally support the Java 8 date/time API, and that `joda-time` will be completely optional. Java 8 also allows for a couple of performance improvements and generally simpler code, also opening the doors to gradually remove Guava as a runtime dependency (which likely wont happen in 5.x yet). There are definitely benefits in Java 8 for `querydsl-sql`, its just that no changes turned out to be required for `querydsl-jpa`  because the ORM vendor does the heavy lifting.

I am pretty far with my changes:
* https://github.com/querydsl/querydsl/pull/2672  (Java 8)
* https://github.com/querydsl/querydsl/pull/2674 (Java 9+ support)
* https://github.com/querydsl/querydsl/pull/2676 (replacing Guava)
