### ISSUE TITLE
Question for Using having and Expression.stringTemplate 

### ISSUE THREAD

**Issue by rxxy** [querydsl/querydsl#2635]
In jpa,
```
StringTemplate dateExpr = Expressions.stringTemplate("DATE_FORMAT({0},'%Y-%m-%d')", qTask.createdTime);
JPAQuery<Tuple> query = qf.select(dateExpr, qTask.count())
       .from(qTask).where(qTask.seller.eq(seller))
       .groupBy(dateExpr).having(dateExpr.goe("2020-03-13"));
```

Generate sql is 
```
SELECT
	date_format( task0_.created_time, '%Y-%m-%d' ) AS col_0_0_,
	count( task0_.id ) AS col_1_0_ 
FROM
	br_task task0_ 
WHERE
	( task0_.deleted = 0 ) 
	AND task0_.seller_id = ?
GROUP BY
	date_format( task0_.created_time, '%Y-%m-%d' ) 
HAVING
        date_format( task0_.created_time, '%Y-%m-%d' )>= ?

```

expect correct sql is
```
SELECT
	date_format( task0_.created_time, '%Y-%m-%d' ) AS col_0_0_,
	count( task0_.id ) AS col_1_0_ 
FROM
	br_task task0_ 
WHERE
	( task0_.deleted = 0 ) 
	AND task0_.seller_id = ?
GROUP BY
	date_format( task0_.created_time, '%Y-%m-%d' ) 
HAVING
	col_0_0_>= ?
```

How to do can make having sub statement use alias `col_0_0_`?

**Comment by jwgmeligmeyling** [comment]
Using a select alias is not allowed in a having clause in JPQL. JPQL does allow a select alias to be referenced in an order by clause, which works as follows:

```java
DateTimePath<Date> alias = Expressions.dateTimePath(Date.class, "alias");

JPAQuery<Tuple> query = qf.select(dateExpr.as(alias), qTask.count())
       .from(qTask).where(qTask.seller.eq(seller))
       .groupBy(dateExpr).having(dateExpr.goe("2020-03-13"))
      .orderBy(alias.asc());
```

As many SQL dialects also allow select aliases to be referenced from the group by clause, I proposed an enhancement for Hibernate to support this as well in their HQL: https://github.com/hibernate/hibernate-orm/pull/3022 . This feature is available since Hibernate 5.4.10.

However, none of the SQL dialects that I am aware of support referencing select aliases in the having clause. For example the following SQL fails under PostgreSQL:

```sql
select a*2 as b from (values (1), (2), (3)) x(a) having b > 4;
```

Therefore, what you want cannot be done in HQL nor JPQL, because it simply cannot be done in plain SQL.
