### ISSUE TITLE
Plans for Mongo 4.X support?

### ISSUE THREAD

**Issue by jmpicnic** [querydsl/querydsl#2681]
Just a question at this point to see if there are any plans to move to Mongo 4.X Drivers. If I get some guidance I'd try to give them a try and build with them.

On a related question, is there a roadmap/backlog (even tentative) for the mongo sub-project?

Thanks a lot in advance.

**Comment by jwgmeligmeyling** [comment]
Would https://github.com/querydsl/querydsl/pull/2239 bring this 4.x support?

Currently querydsl-mongodb is only community supported, so there is not really a roadmap. Most issues labeled MongoDB in the issue tracker arent even feature requests but rather questions. What features would you like to see?

**Comment by jmpicnic** [comment]
Thanks a lot for taking the time to answer it.  

It seems it would get us a whole lot closer. As of now it is not a matter of specific features (although some of the new pipeline operators would be nice) as we are just bootstrapping a new project. The main reason to try to go to the 4.x series is to avoid old bugs, incompatibilities and the like. We have talked to Mongo and they poo-pooed Query

It seems that #2239 is a "dead" PR. @mp911de, are you planning to resurect it as you mention in your last comment in that thread? Also, I didn't see any changes to the dependencies in the build configurations, so I am not sure whether you (@mp911de) were planning to update it to 4.X (4.0.5 I think is the latest production version following Mongo's even/odd convention).

Thanks again

**Comment by mp911de** [comment]
I'm happy to help. Reactions to comments don't pop up in GitHub notifications. The mentioned PR is defunct because I removed in the meantime my repository. Let me create a new pull request and close the existing one.

**Comment by jwgmeligmeyling** [comment]
> It seems that #2239 is a "dead" PR.

That PR was left idle for a while. That's actually not so much MongoDB specific, but unfortunately applies to QueryDSL as a whole. The project recently got transfered to new maintainers. I am personally currently working hard on pushing a 5.0.0 release which solves a few long known issues like Hibernate 5.x, Java 8 and Java 9+ compatibility.

A lot of stale PRs remained unmerged due to a somewhat "breaking" API change. While this sounds very drastic, even a dependency version bump is considered a breaking change. Now we're working on a new major release, we have a lot more flexibility regarding the introduction of (slightly) breaking changes. I would like to use this opportunity to refresh the `querysql-mongodb` integration as well.

@mp911de looking forward to your new PR, I would definitely integrate it.

@jmpicnic could you please let me know what further changes are required after the PR to make 4.x support happen? I am personally not a user of `querydsl-mongodb` so its difficult for me to try it out in the wild.

**Comment by jmpicnic** [comment]
Thanks a lot to both of you. Let me check with my colleagues here and will get back to you on what we would like to see. As I mentioned, we are starting a new project and we are "reconnecting" with both Mongo and QueryDSL after a few years of distance. 

Thanks.

**Comment by mp911de** [comment]
I submitted a new pull request (#2689) as the old PR #2239 pointed to a deleted repository.

**Comment by jwgmeligmeyling** [comment]
That PR is now closed and will be included in the next 5.0 release.
