### ISSUE TITLE
[querydsl-sql] Cannot find any documentation how to config code generation part in maven-compiler-plugin

### ISSUE THREAD

**Issue by aaramg** [querydsl/querydsl#2777]
Hi.
When I was using 'querydsl-jpa', I could find a way to config the code generation in 'maven-compiler-plugin' in 'annotationProcessorPaths' 'path'. But now I use 'querydsl-sql-spring' and try to use it the same way, but could not find a way to do that. I have done the configuration with 'querydsl-maven-plugin'. But I want the code generations in one place if it is possible.

Also the second point. Is it possible to configure the plugins without mentioning 'jdbcUrl', 'jdbcUser', or 'jdbcPassword'. I have my db column names on top of @Entity class fields with annotation @Column, f.ex `@Column(name = "display_format", nullable = false)`

**Comment by jwgmeligmeyling** [comment]
`querydsl-sql` and `querydsl-jpa` require completely different means of metamodel generation.

You could see if [`JPASQLQuery`](https://github.com/querydsl/querydsl/blob/master/querydsl-jpa/src/main/java/com/querydsl/jpa/sql/JPASQLQuery.java) is something for you. It works on the JPA metamodel instead of a QueryDSL SQL metamodel.
