### ISSUE TITLE
Remove `MongoCollection` argument from `AbstractFetchableMongodbQuery` constructor in favor of `getCollection`

### ISSUE THREAD

**Issue by mp911de** [querydsl/querydsl#2914]
## Why the new feature should be added

To give integrations more control over the target collection, it would make sense to declare an abstract method `getCollection` so that `AbstractFetchableMongodbQuery` can request the target collection on demand. There's a similar arrangement for `getCollection(Class)` which helps to delay collection retrieval for multi-tenancy arrangements.

**Comment by jwgmeligmeyling** [comment]
Why is a `getCollection()` method needed over just invoking `getCollection(Document.class)`?

Also, do we still want to initialize the field in the constructor and store it in a field? Because I believe calling object methods from the constructor is a bit of an any pattern (as the object is not properly initialized yet). Perhaps we could just lazily invoke `getCollection()` in `fetchCount()` and `createCursor()`?

Just trying to make sure I am creating the patch as the issue intends to.

**Comment by mp911de** [comment]
> Why is a getCollection() method needed over just invoking getCollection(Document.class)?

This is probably specific to Spring Data as `Document.class` is a MongoDB type and not the target entity type so we'd need always a `if` to check whether the actual collection or a target class collection is meant. By splitting responsibilities, that would become more clear.

> Also, do we still want to initialize the field in the constructor and store it in a field?

Rather not.

> Perhaps we could just lazily invoke getCollection() in fetchCount() and createCursor()?

That's the underlying intention.
