### ISSUE TITLE
Querydsl has Spring Roo maven links

### ISSUE THREAD

**Issue by gregturn** [querydsl/querydsl#3005]
The following spots have hard coded links for Roo dependencies:

* https://github.com/querydsl/querydsl/blob/master/querydsl-apt/pom.xml#L262-L268
* https://github.com/querydsl/querydsl/blob/master/pom.xml#L691

This needs to be updated. Perhaps as optional dependencies?

Related: https://github.com/spring-projects/spring-data-jpa/issues/2285

**Comment by jwgmeligmeyling** [comment]
`querydsl-core` has no dependency to `spring-roo`. `querydsl-dsl` has one, but its already optional and in the provided scope. The issue here seems not to be the dependency on `spring-roo`, but rather the inclusion of a no longer (or not always) available Maven repository.

In Querydsl 5.0 we updated Spring Roo to a more widely available version, so we should be able to get rid of that repository altogether.

Otherwise I am willing to drop Spring Roo support. We're trying to get rid of most unsupported Querydsl modules anyway.

**Comment by michael-simons** [comment]
roo is on central anyway. There is no point of having that hardcoded dependency.

**Comment by jwgmeligmeyling** [comment]
Its legacy, Spring Roo dependency was only bumped to a publicly available version since the 5.0.0 release.

**Comment by burricks** [comment]
Hi, I am interested in closing this issue as a first contribution to querydsl. Based on these comments, it seems that I am just supposed to remove the references to the spring too repository at the two mentioned locations. Is this correct? If so, I will submit a PR with those references removed. 

@jwgmeligmeyling @michael-simons @gregturn

**Comment by jwgmeligmeyling** [comment]
In essence that should be it 👍🏻

**Comment by burricks** [comment]
@jwgmeligmeyling I submitted a PR that removes these dependencies if you'd like to take a look. Is there any way that I could write a unit test to validate this work, like a test that there is no dependency to SpringRoo or something along those lines...

**Comment by Frettman** [comment]
Any idea when this will be published in a release?
