### ISSUE TITLE
Support other means of identifying  entities, embeddables etc. other than annotations

### ISSUE THREAD

**Issue by odrotbohm** [querydsl/querydsl#3025]
Currently, even the core `Configuration` abstraction of the APT assumes that entities and embeddables are identified by annotations. While that's fine for most cases, there have been other approaches popping up [jMolecules](https://github.com/xmolecules/jmolecules) recently that rather identify those concepts by types. E.g. in jMolecules, an entity would implement the `Entity` interface, embeddables would either be `Identifier`, `Association` or `ValueObject`.

I'd love to see a variant of `Configuration` that rather asks for `Predicate` instances and some helper code so that I can easily implement a `Configuration` like this:

```java
class MyConfiguration implements NewConfiguration {

  Predicate<…> getEntitiesPredicate() {
    return Predicates.implements(Entity.class);
  }
}
```

The current implementation could then be adapted to by:

```java
class LegacyConfigurationAdapter implements NewConfiguration {

  private final Configuration delegate;

  Predicate<…> getEntitiesPredicate() {
    return Predicates.isAnnotatedWith(delegate.getEntitiesAnnotation());
  }
}
```

I'm not very knowledgeable about developing APT plugins but would be happy to help to draft a prototype if you think it's worth pursuing.

**Comment by jwgmeligmeyling** [comment]
While the reflection API is quite powerful, the APT API can be quite limiting. Blending the two does not always play nicely, because the classes itself can be under compilation.

By splitting a few pieces of code up in methods that can be overridden in the [`AbstractQuerydslProcessor`](https://github.com/querydsl/querydsl/blob/master/querydsl-apt/src/main/java/com/querydsl/apt/AbstractQuerydslProcessor.java#L128-L145), you should be able to delegate a fair amount of work to the configuration. I'd definitely be willing to integrate such a change.
