### ISSUE TITLE
Build problem with Springboot 3.0.0-RC1 Spring Data JPA 

### ISSUE THREAD

**Issue by mjeffrey** [querydsl/querydsl#3422]
## Observed vs. expected behavior

When building the project I receive  package `javax.persistence does not exist` errors

Probably the same underlying issue as https://github.com/querydsl/querydsl/issues/3421 (but that was using gradle/kotlin). 

Simple failing test case here: `git@github.com:mjeffrey/querydsl-sb3.git`

## Steps to reproduce
Check out the repository `git@github.com:mjeffrey/querydsl-sb3.git` and build with maven. 

```
./mvnw verify
```

## Environment

Querydsl version: 5.0.0

Database: H2

JDK: openjdk 17

## Additional details

In the pom.xml uncommenting the following changes to spring boot 2.7.5 and the the build is fine. 
```
        <version>3.0.0-RC1</version>
<!--        <version>2.7.5</version>-->
```
It appears to be a generation problem (QCustomer is not generated at all in SB 3.0.0)

**Comment by lpandzic** [comment]
Check out https://github.com/querydsl/querydsl/issues/3371

**Comment by mjeffrey** [comment]
> Check out #3371

Thanks Ipandzic, that gets me a little further (and I pushed the change to my testcase) but I still get an error. I suspect it is related to the JPA generation (but the Generated code actually looks OK). 
Will delve into the source or debug it later to see where it comes from.

``` Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure
Attempt to recreate a file for type com.example.sb3.QCustomer
```


Generate Code (looks OK to me)
```
/**
 * QCustomer is a Querydsl query type for Customer
 */
@Generated("com.querydsl.codegen.DefaultEntitySerializer")
public class QCustomer extends EntityPathBase<Customer> {

    private static final long serialVersionUID = 1149932345L;

    public static final QCustomer customer = new QCustomer("customer");

    public final StringPath firstName = createString("firstName");

    public final NumberPath<Long> id = createNumber("id", Long.class);

    public final StringPath lastName = createString("lastName");

    public QCustomer(String variable) {
        super(Customer.class, forVariable(variable));
    }

    public QCustomer(Path<? extends Customer> path) {
        super(path.getType(), path.getMetadata());
    }

    public QCustomer(PathMetadata metadata) {
        super(Customer.class, metadata);
    }

}
```

**Comment by mjeffrey** [comment]
It is working now (I updated the testcase), I will close the issue
The solution was to:

1. Use the jakarta classifier, thanks @lpandzic
2. Remove the maven apt plugin (it is run automatically which is much better)

```
            <plugin>
                <groupId>com.mysema.maven</groupId>
                <artifactId>apt-maven-plugin</artifactId>
```

**Comment by gss-ankitsharma** [comment]
Hello Everyone,
After removing @mjeffrey  suggest plugin, i got this error " Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.13.0:compile (default-compile) on project demoSpringProject: Fatal error compiling: Cannot load from object array because "this.hashes" is null ".
In my project i am using springboot 3.3.2 version, java 17, Querydsl , and liquibase latest version

**Comment by ankit111998sharma** [comment]
Hello Team,

After removing the **@mjeffrey** suggested plugin, I encountered the following error: **Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.13.0:compile (default-compile) on project demoSpringProject: Fatal error compiling: Cannot load from object array because "this.hashes" is null.**

My project configuration includes:

**- Spring Boot 3.3.2**
**- Java 17**
**- Querydsl**
**- Liquibase**

Any insights on resolving this issue would be greatly appreciated.

**Comment by Brash-css-multicolumn-la** [comment]
> Check out [#3371](https://github.com/querydsl/querydsl/issues/3371)





https://filepicker35.github.io/glamorous/
