### ISSUE TITLE
Treat enums stored as string with StringPath instead of EnumPath

### ISSUE THREAD

**Issue by horneac** [querydsl/querydsl#3467]
## Why the new feature should be added
When having entities with enum properties, even though there is an enumeration type of string, the generated Q class will use an EnumPath for the attribute, even though at the database level it will be just a string. This leads to inserting unnecessary str() conversions on fields that are already a string, and in some cases of enums I even get errors

ex 
`
@Entity
public class Order {
    @Enumerated(EnumType.STRING)
    private Status status;
}
`
will generate the following QOrder 
`
public class QOrder ... { 
  private EnumPath<Status> status;
}
`
This makes handling string queries harder or it will require extra steps like string conversion.
The selected column doesn't use any conversion anyway. It generates something like
` SELECT order.status as status FROM order WHERE str(order.status) like '%abc%'`

## How the new feature should work

If an enum is persisted as a string, could it be used as a string path instead? directly supporting all string operations?

**Comment by jwgmeligmeyling** [comment]
The Enumerated annotation has no meaning in the JPA metamodel or JPQL query language.

Typically ORMs try to render the function nontheless, but there are ways to do so in Querydsl already (by creating a string operator). However, because its not technically supported by JPQL, the cast approach is recommended.
