### ISSUE TITLE
QClasses are not generated in a multi-module Maven project

### ISSUE THREAD

**Issue by simasch** [querydsl/querydsl#3599]
I use Spring Boot 3.1.4 and I've configured the dependencies in each module where QueryDSL is used

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>

        <dependency>
            <groupId>com.querydsl</groupId>
            <artifactId>querydsl-jpa</artifactId>
            <version>${querydsl.version}</version>
            <classifier>jakarta</classifier>
        </dependency>
        <dependency>
            <groupId>com.querydsl</groupId>
            <artifactId>querydsl-apt</artifactId>
            <version>${querydsl.version}</version>
            <classifier>jakarta</classifier>
            <scope>provided</scope>
        </dependency>

But no QClasses are generated.

If I use the exact same dependencies in a single module Spring Boot project everything works fine.

Any idea what the difference could be?

**Comment by SebastianDietrich** [comment]
Hmm - I have such a multi-module maven project with querydsl.
The most important difference is the following:
                
                <plugin>
                    <groupId>com.mysema.maven</groupId>
                    <artifactId>apt-maven-plugin</artifactId>
                    <version>${apt-maven-plugin.version}</version>
                    <executions>
                        <execution>
                            <goals>
                                <goal>process</goal>
                            </goals>
                            <configuration>
                                <outputDirectory>target/generated-sources/java</outputDirectory>
                                <processor>com.querydsl.apt.jpa.JPAAnnotationProcessor</processor>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>

**Comment by simasch** [comment]
@SebastianDietrich The Maven Plugin is no longer necessary. 
@scordio, unfortunately, this didn't help and shouldn't be required.

I really don't understand why it works in a single-module project and not in my multi-module setup.

**Comment by scordio** [comment]
@simasch out of curiosity, what is not required? The compiler plugin configuration?

**Comment by SebastianDietrich** [comment]
Just checked - when I remove that plugin, it no longer works on my side.
Where do you have the info from, that it is no longer necessary?

**Comment by scordio** [comment]
AFAIK, you have somehow to plug the `com.querydsl.apt.jpa.JPAAnnotationProcessor` into the compiling phase. This can be done via the `maven-compiler-plugin` or via the `apt-maven-plugin`.

I personally prefer the former to avoid third-party plugins but it's definitely personal taste.

**Comment by simasch** [comment]
@SebastianDietrich as I wrote I have a project where I don't need to use the plugin

**Comment by bwgjoseph** [comment]
> AFAIK, you have somehow to plug the `com.querydsl.apt.jpa.JPAAnnotationProcessor` into the compiling phase. This can be done via the `maven-compiler-plugin` _or_ via the `apt-maven-plugin`.
> 
> I personally prefer the former to avoid third-party plugins but it's definitely personal taste.

I've tried the `compiler-plugin` method but it doesn't generate for me as well. Have to fall back to `apt-plugin`.

**Comment by scordio** [comment]
@simasch @bwgjoseph I just tried a simplified multi-module setup with the compiler plugin in a fresh Spring Boot 3.1.4: https://github.com/scordio/spring-boot-querydsl-example/commit/3d68f800b6646bac146d65f458836b84ec1fe6d6

It seems to work fine:

![Screenshot 2023-09-28 at 18 55 11](https://github.com/querydsl/querydsl/assets/26772046/a5329493-06f2-4f71-beb6-ace66ed11baa)

I also tried the dependency-only config in a single module app and indeed it works fine, I guess because of the default annotation processors discovery process mentioned in the [`annotationProcessors`](https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html#annotationProcessors) parameter documentation. I wasn't aware of it! 🙂 

Also, if I try the same in the multi-module example, it also works: https://github.com/scordio/spring-boot-querydsl-example/commit/9c55ceaa09cfa05db8b718fbcccf5f589afbbb76

Could it be that you have a maven compiler configuration in a parent module that specifies some annotation processors? According to the [`annotationProcessors`](https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html#annotationProcessors) documentation, having specific annotation processors would prevent the automated discovery from the classpath.

For example, I tried to add the MapStruct processor, and the QueryDSL classes are no longer generated: https://github.com/scordio/spring-boot-querydsl-example/commit/fe54d1bd48c3dfcf65917bcc39361d98a47c3684

**Comment by robert-niestroj** [comment]
<plugin>
                <groupId>com.mysema.maven</groupId>
                <artifactId>apt-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>process</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>target/generated-sources/java</outputDirectory>
                            <processor>com.querydsl.apt.jpa.JPAAnnotationProcessor</processor>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

> Hmm - I have such a multi-module maven project with querydsl. The most important difference is the following:
> 
> ```
>                 
>                 <plugin>
>                     <groupId>com.mysema.maven</groupId>
>                     <artifactId>apt-maven-plugin</artifactId>
>                     <version>${apt-maven-plugin.version}</version>
>                     <executions>
>                         <execution>
>                             <goals>
>                                 <goal>process</goal>
>                             </goals>
>                             <configuration>
>                                 <outputDirectory>target/generated-sources/java</outputDirectory>
>                                 <processor>com.querydsl.apt.jpa.JPAAnnotationProcessor</processor>
>                             </configuration>
>                         </execution>
>                     </executions>
>                 </plugin>
> ```

This works in my SB 2.7 Project

**Comment by simasch** [comment]
Thank you very much @scordio 

I'll investigate further tomorrow.

**Comment by bwgjoseph** [comment]
Thanks @scordio.

I do have other annotation processor where one of them is mapstruct. I think I tried some ordering but it wouldn't work for querydsl hence I have to fallback to apt plugin.

I'm not sure if it's apt plugin or intellij config, but intellij is not reliable in terms of regenerating the qclasses whenever I have changes. Hence, I have to run clean compile manually to get the updated qclass.

One more common scenario is when I create new class where I expect the qclass to also get generated but it doesn't.

**Comment by scordio** [comment]
@bwgjoseph what if you try to rely on the automated discovery only? It means having the artifacts with the annotation processors as dependencies with the `provided` scope and no [annotationProcessors](https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html#annotationProcessors) configuration on the `maven-compiler-plugin`.

I've tried it in https://github.com/scordio/spring-boot-querydsl-example/commit/a8911ddc27aefb2147152e87394590c249f7e96d

**Comment by bwgjoseph** [comment]
I have to test it out but then again, there's further complication as well because the project also uses Lombok. Which there need to have configuration done for Lombok to work with mapstruct in the compiler plugin. :(

**Comment by arnosthavelka** [comment]
@simasch what do you mean by multi-maven project? To use it via dependency management or just in module? Because it seems working in my case -> see https://github.com/arnosthavelka/spring-advanced-training/blob/develop/sat-jpa/pom.xml. I also tried usage via dependency management (see https://github.com/arnosthavelka/spring-advanced-training/tree/querydsl-dependency-management-uasage) and it seems working as well.

I guess you just need always specify the classifier.

**Comment by exaucae** [comment]
facing the exact same issue. I first discribed it in the spring data mongo repository before being redirected here: https://github.com/spring-projects/spring-data-mongodb/issues/4549.

My setup is using Kotlin and Gradle though
