### ISSUE TITLE
Escape character in LIKE expressions is not escaped by querydsl

### ISSUE THREAD

**Issue by LordOfTheHelmet** [querydsl/querydsl#438]
To reproduce this:

``` java
BooleanExpression patternPredicate = company.name.toLowerCase().like("%My! Text%");
```

When i execute this i get the exception:

``` java
java.sql.SQLDataException: ORA-01424: Zeichen nach dem Escape-Zeichen fehlen oder sind ungültig
```

The SQL generated from the expression looks like:

``` sql
lower(company0_.NAME) like ? escape '!'
```

and the bound value is:

``` java
TRACE org.hibernate.type.descriptor.sql.BasicBinder.bind(BasicBinder.java:84) - binding parameter [1] as [VARCHAR] - %My! Text%
```

Shouldn't querydsl escape the escape character for me? Otherwise i have to do something like:

``` java
BooleanExpression patternPredicate = company.name.toLowerCase().like("%My! Text%".replaceAll("!", "!!"), '!');
```

**Comment by ciprian197** [comment]
Hello, the approach with `str.like("\\%", '\\')` does not seem to work when using SQLQuery and having MariaDB as database (I tried also with MySQLTemplates and also with SQLTemplates). The generated where clause looks like`'test\_random\_' escape '\'` which results in a syntax exception due to the escaping of the quote character. If needed I can provide better examples.
