### ISSUE TITLE
JPA: Allow expressing COUNT DISTINCT for multiple fields

### ISSUE THREAD

**Issue by Maia-Everett** [querydsl/querydsl#669]
Currently, to express COUNT(DISTINCT field) for a single field, I can write `uniqueResult(q.field.countDistinct())`, but there is no syntax for multiple fields like COUNT(DISTINCT field1, field2, ...).

**Comment by renanleandrof** [comment]
Hello,
 sorry for ressurrecting this issue, but is there any workaround? I don't wanna loose the JPAQuery good things because of this.. =/

I have some querys that uses Sum() and group by. When i use the .fetchCount() method it generates a query with count(distinct colum1, column2, column3 ...). I also tried to do a subquery but JPQL doesn't support ...
